"""create_driver_states

Revision ID: fcce49a3b5bb
Revises:
Create Date: 2026-05-15 15:00:02.036651

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fcce49a3b5bb"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "driver_states",
        sa.Column("driver_id", sa.String(length=64), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lng", sa.Float(), nullable=False),
        sa.Column(
            "status", sa.String(length=32), server_default=sa.text("'online'"), nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("driver_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("driver_states")
    # ### end Alembic commands ###
